server:
  port: 8080
spring:
  application:
    name: "NameProject"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
mailSend:
  host: "smtp.gmail.com"
  port: 587
  username: "arquitech2023@gmail.com"
  password: "haxjqvjgrvvfwdyz"
  starttls.enable: true
  smtp.auth: true
  include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
